name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission to Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Build ShadowJar
      run: ./gradlew shadowJar

    - name: Upload plugin jar as GitHub Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NoVoidX-Plugin
        path: build/libs/NoVoidX-all.jar

    - name: Send .jar to Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        echo "Mengirim file ke Discord..."
        curl -F "payload_json={\"content\": \"✅ Build selesai! Plugin NoVoidX berhasil dibuat.\"}" \
             -F "file=@build/libs/NoVoidX-all.jar" \
             $DISCORD_WEBHOOK
