jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with ShadowJar
      run: ./gradlew shadowJar

    - name: Upload plugin jar
      uses: actions/upload-artifact@v4
      with:
        name: NoVoidX-Plugin
        path: build/libs/NoVoidX-all.jar
