name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission to Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Build ShadowJar
      run: ./gradlew shadowJar

    - name: Send jar to Discord with versioned name
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        VERSION=$(./gradlew properties -q | grep "^version:" | awk '{ print $2 }')
        JAR_NAME="NoVoidX-${VERSION}.jar"
        echo "Uploading $JAR_NAME to Discord..."
        curl -F "payload_json={\"content\": \"✅ Build NoVoidX ${VERSION} selesai!\"}" \
             -F "file=@build/libs/${JAR_NAME}" \
             $DISCORD_WEBHOOK
